---
title: "Analysis of accessibility from collection and delivery points: towards the sustainability of the e-commerce delivery"
date: "`r Sys.Date()`"
author:
  - name: Renata Lúcia Magalhães de Oliveira
    url: https://retaoliveira.github.io/blog
    affiliation: Federal Center for Technological Education of Minas Gerais
    affiliation_url: www.cefetmg.br
    orcid_id: 0000-0002-9011-2342
journal: 
  title: "urbe. Revista Brasileira de Gestão Urbana"
doi: "10.1590/2175-3369.011.e20190048"
citation_url: https://doi.org/10.1590/2175-3369.011.e20190048
output: distill::distill_article
---

<link rel="stylesheet" href="academicons-1.9.1/css/academicons.min.css"/>

## Abstract

The collection and delivery points (CDP) are an alternative to home deliveries and an important opportunity to reduce failed deliveries within urban areas. In this study, we propose to analyze the accessibility from CDPs located in commercial establishments (drugstores, gas stations, post offices, supermarkets, and malls) considered most attractive by e-consumers to receive this delivery solution. The methodological approach uses spatial analysis to identify the coverage area of the CDPs considering socioeconomic data and e-consumer preferences. Also, spatial tools to analyze the accessibility of CDPs were used, considering the transport infrastructure, the population location, and job opportunities location through different transport modes. The results indicated differences in levels of accessibility between the CDPs, highlighting the important associations among economic activities, land use patterns, and transport to plan for sustainable cities. The use of cluster analysis methods as a methodological approach is one contribution and can be replicated to support decision-making in other cities.

## Keywords
Urban freight transport; Collection and delivery points; Accessibility; E-commerce delivery; Last-mile delivery
 <a href="#top">Back to top</a>