---
title: "Accessibility to Food Retailers: The Case of Belo Horizonte, Brazil"
date: "`r Sys.Date()`"
author:
  - name: Renata Lúcia Magalhães de Oliveira
    url: https://retaoliveira.github.io/blog
    affiliation: Federal Center for Technological Education of Minas Gerais
    affiliation_url: www.cefetmg.br
    orcid_id: 0000-0002-9011-2342
journal: 
  title: "Sustainability"
doi: "10.3390/su12072654"
citation_url: https://doi.org/10.3390/su12072654
output: distill::distill_article
---

<link rel="stylesheet" href="academicons-1.9.1/css/academicons.min.css"/>

## Abstract

Access to food products is essential to sustain life. In this paper, we discuss the differences concerning accessibility levels to food retailers among potential consumers in Belo Horizonte, Brazil. The goal was to characterize spatial mismatches regarding opportunities to access food and identify suitable areas for sustainable last food mile solutions, such as non-motorized home delivery and purchase trips. For this, we have spatially related: (i) the population concentration; (ii) the income of households and (iii) accessibility measures considering both the spatial structure of food retailers and the distance between households and stores, considering the food last mile. We have then used spatial statistics (Global Moran’s I index, average nearest neighborhood analysis) and spatial analyses (overlay and processing) to determine the spatial pattern and the relation of the variables population, income, and accessibility to food retailers. We have considered the cumulative-opportunity measure, which is an indicator of the number of opportunities that can be reached within a time threshold. There is great spatial differentiation regarding the accessibility levels of food retailers and the results can be considered to support the development of policy and land use regulation that can stimulate non-motorized and collaborative delivery as an effective last-mile solution

## Keywords
Accessibility; food service facilities; grocery retailers; city logistics; last mile delivery

 <a href="#top">Back to top</a>