---
title: "An Overview of Problems and Solutions for Urban Freight Transport in Brazilian Cities"
date: "`r Sys.Date()`"
author:
  - name: Renata Lúcia Magalhães de Oliveira
    url: https://retaoliveira.github.io/blog
    affiliation: Federal Center for Technological Education of Minas Gerais
    affiliation_url: www.cefetmg.br
    orcid_id: 0000-0002-9011-2342
journal: 
  title: "Sustainability"
doi: "10.3390/su10041233"
citation_url: https://doi.org/10.3390/su10041233
output: distill::distill_article
---

<link rel="stylesheet" href="academicons-1.9.1/css/academicons.min.css"/>

## Abstract

Urban freight transport is a challenge for Brazilian cities due to the lack of adequate planning for freight flow movement. Public managers also show negligence and a lack of awareness when dealing with urban logistics. Decision-support data on urban freight transport are still scarce, despite being of fundamental value to economic development. With this in mind, this paper presents problems and solutions regarding urban freight transport in Brazilian cities. Data were obtained through a survey conducted in nine cities and analysed by means of descriptive statistics and the successive intervals method. Additionally, a cluster analysis was performed to identify patterns regarding the typical characteristics of each city in order to compare and generalise the perception of retailers regarding problems and solutions at the national level. The results indicate divergent opinions among retailers from different cities, even from cities with similar socioeconomic profiles and urban dynamics. The municipalities which demonstrated the most similarities were (i) Betim and Niteroi, in the Southeast of Brazil; (ii) Palmas and Quixada, in the North and Northeast, respectively; and (iii) Palmas and Caruaru, also in the North and Northeast. The results reinforce the importance of studying the local context and involving stakeholders in the process of planning urban logistics solutions.

## Keywords
Urban freight transport; retailers’ perceptions; method of successive intervals; city logistics; problems; solutions; cluster analysis; urban network hierarchy; Brazil

 <a href="#top">Back to top</a>