---
title: "Research Projects"
author: "Renata Lúcia Magalhães de Oliveira"
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    css: styles.css
    toc: true
    toc_depth: 3
---
<link rel="stylesheet" href="academicons-1.9.1/css/academicons.min.css"/>

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Accessibility as an urban planning paradigm for more sustainable and equitable cities

The structure of thought that underlies the classical models of transportation planning considers this activity as a sovereign element for the economic development of cities and for the access to activities essential to the urban way of life. However, epistemological discussions about the need to structure more holistic analyses to support the decisions of the different actors involved in the planning of cities have been highlighted. 

This paradigm shift already appears in integrated urban planning studies, through which subsystems are modeled in an integrated manner, namely: the location of activities, land use, and transportation structure (Banister, 2008; Macário, 2014; Sousa et al., 2017). More recently, according to Garcia et al. (2018), urban accessibility planning with a focus on sustainability and equity has been considered the best approach for dealing with complex urban processes and their impacts on citizens' quality of life. 

In this context, it is aimed to develop studies to understand the complexity of the urban dynamics of Brazilian cities and the causal relationships of phenomena related to the dynamics of human activities, land use and mobility. The results of these studies will contribute to conceptual and methodological improvements in urban planning in the Brazilian context, at different scales and localities, adding value to the theoretical and methodological framework existing in the literature and subsidizing decision making regarding structural urban elements with greater assertiveness.


## Spatial Analysis applied to Urban Logistics

The urban distribution of goods is necessary to sustain the way of life in cities. However, several negative impacts related to this activity in urban areas are identified, such as: increased congestion, emission of pollutants, increased noise, less efficient transport operating conditions, among others. Thus, urban logistics, which aims to promote solutions to reduce these impacts, ensuring efficiency in the movement of goods, has been the object of investigation of researchers and professionals in Transport Engineering and related areas. 

Consequently, quantitative methods are usually employed in the treatment of the aforementioned problems, considering, almost exclusively, the relationships between the identified attributes. On the other hand, even though transportation is an intrinsically spatial phenomenon, the problems, the challenges and the proposition of solutions for urban logistics are not commonly discussed considering the location of these activities in space. The spatialization of information and spatial analysis techniques can add significant value to the analysis related to the urban distribution of goods. 

Thus, this project aims to relate the different problems faced to perform freight transport in urban areas and the techniques of spatial information processing and spatial analysis, aiming to structure a new methodological guideline for studies of this nature. Various publications on urban logistics will be explored for the identification and characterization of the problems faced in the execution of these activities. In addition, spatial techniques will be discussed and different free or open source software will be identified and explored for computational implementation. Real data, collected in other researches, will be used to validate the methodological proposals. These techniques will be explored from the point of view of several actors of the urban logistics and can be useful both in the proposition of solutions and consequent subsidy to the definition of public policies, and to the increment of the teaching methodology in the area of Transport Engineering.


## Railroads and economic development

Railroads are structurally complex systems and demand important financial contributions in investments and operational costs. However, the competitive advantages compared to other land modes are significant and reflect gains related to: (i) energy and operational efficiency, through gains of scale; (ii) lower environmental impacts both in installation and operation, with lower greenhouse gas emissions and other environmental externalities promoted by the movement of people and goods; and (iii) high transport capacity and gains in service level. Railroad transportation in Brazil presents structural problems. 

Considering the movement of cargo in Brazil, there is a strong concentration in the use of the highway system (about 60% of transport production), even in the face of the predominance of commodity flows from the interior of the country to the international market. Railroads account for only a little more than 20% of this production. Taken together, Brazil's subway network is shorter than the systems of New York, Tokyo, Shanghai and London individually. Furthermore, in regional terms, there are only two passenger rail lines which operate in shared sections with freight. 

Thus, it becomes necessary to promote public policies and actions that seek (i) greater accessibility; and (ii) greater spatial and socioeconomic equity. Therefore, through this project, we intend to carry out a macro analysis of the Brazilian railroad sector on an urban and regional scale, for the transportation of cargo and people. Then, locational characteristics of the urban and regional demand for rail transport will be confronted and, finally, directions for remodeling the current system and proposing new investments in the Brazilian railroad structure will be proposed, aiming to promote greater spatial equity in the distribution of rail transport supply and in promoting economic integration in Brazil. Two projects are allocated under this umbrella project, namely: (i) Railway Macroanalysis: proposals for brazil (ii) Proposals for the Brazilian Railway System: an approach based on accessibility and sustainability.


 <a href="#top">Back to top</a>
